CREATE TABLE atividade(
    id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    funcionario VARCHAR(250) NOT NULL,
    descricao VARCHAR(250) NOT NULL,
    tipo VARCHAR(250) NOT NULL,
    horas INT NOT NULL,
    PRIMARY KEY(id)
);

